### PR TITLE
Add filter by season helper

### PR DESCRIPTION
**Pull request by jdcarey128**
This PR: 
- Creates a filter by season helper method 
- Updates sum_game_goals and highest/lowest_goals to include helper

### CODE REVIEW

**Review by dunlapww — APPROVED** [review]
Hey Joshua, I didn't use this modified method for mine yet, but think it could be useful for refactor i'll likely do.  Ok to merge in.

**Comment by jakeheft** [comment]
Looks good, Joshua; just need to update tests with added sample data.

**Comment by hopesgit** [comment]
Looks good otherwise, but I'm not approving it until those merge conflicts are fixed.

**Review by hopesgit — CHANGES_REQUESTED** [review]
I should have left my previous comment here. Once merge conflicts are addressed, all is good.

**Comment by jakeheft** [comment]
Requested changes have been made, merging PR.

**Pull request merged**
